// Class automatically generated by Dev-C++ New Class wizard

#include "pilha.h" // class's header file

// class constructor


// class destructor
template<class Object>
Pilha::Pilha(){
               

               
      
              
      
