// Class automatically generated by Dev-C++ New Class wizard

#ifndef PILHA_H
#define PILHA_H
#include<vector>
using std::vector;


/**
 * Classe de Exercicio 2 PAED I
 */
template <class Object>
class Pilha{
public:
   Stack( ) ;
   bool estaVazia( ) const;
   const Object & topo( ) const;
   void tornarVazia( );
   void empilha ( const Object & x );
   Object desempilha( );

private:
   vector<Object> elementos;
   int topoPilha;
};



#endif // PILHA_H
